DELETE FROM security_audit_log 
WHERE action IN (
  'SESSION_START', 'SESSION_END', 
  'SESSION_ACTIVE', 'SESSION_INACTIVE', 
  'SESSION_HEARTBEAT', 
  'WINDOW_BLUR', 'WINDOW_FOCUS', 
  'USER_ACTIVITY', 
  'SELECT', 'SENSITIVE_DATA_ACCESS', 
  'PAGE_NAVIGATION'
);